version: "3.7"
services:
  app:
    build:
      args:
        user: kcsit_user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: kcsittest
    container_name: kcsittest-app
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - db
      - nginx
    volumes:
      - ./:/var/www
    networks:
      - app-network
    # command: /bin/sh -c "entry_point.sh"
      # command: >
    #   /bin/sh -c "cd /var/www 
    #   && composer install 
    #   && composer dump-autoload 
    #   && php artisan key:generate 
    #   && php artisan cache:clear 
    #   && php artisan config:clear 
    #   && php artisan migrate:fresh
    #   && tail -f /dev/null"

  db:
    image: mysql:5.7
    container_name: kcsittest-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: kcsittest-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
